### ISSUE TITLE
problems running with load-grunt-config

### ISSUE THREAD

**Issue by colwilson** [logankoester/grunt-environment#3]
load-grunt-config calls load-grunt-tasks by default and so if you try to use it with grunt-environment it will fail because load-grunt-tasks tries to load grunt-environment before grunt.config is initialized.

so this will fail:

```
module.exports = (grunt) ->
  require("load-grunt-config") grunt,
    config:
      thing: "thingy"
      number: 42

      environment:
        default: "development"
        environments: ["development", "production"]
        version: ->
          grunt.file.readJSON("package.json")["version"]
```

There are two ways around this. EITHER rename grunt-environment so that it does not begin with "grunt", say load-grunt-environment:

```
module.exports = (grunt) ->
  require("load-grunt-config") grunt,
    config:
      thing: "thingy"
      number: 42

      environment:
        default: "development"
        environments: ["development", "production"]
        version: ->
          grunt.file.readJSON("package.json")["version"]

  require("load-grunt-environment") grunt
```

or, probably simpler, do this:

```
module.exports = (grunt) ->
  require("load-grunt-config") grunt,
    loadGruntTasks: false 
    config:
      thing: "thingy"
      number: 42

      environment:
        default: "development"
        environments: ["development", "production"]
        version: ->
          grunt.file.readJSON("package.json")["version"]

  require("load-grunt-tasks") grunt
```

Either way you might want to document this as it makes it obvious that theyy can work together smoothly.
